// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/manga.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Genre struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Genre) Reset() {
	*x = Genre{}
	mi := &file_proto_manga_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Genre) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Genre) ProtoMessage() {}

func (x *Genre) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Genre.ProtoReflect.Descriptor instead.
func (*Genre) Descriptor() ([]byte, []int) {
	return file_proto_manga_proto_rawDescGZIP(), []int{0}
}

func (x *Genre) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Genre) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MangaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Genres        []*Genre               `protobuf:"bytes,4,rep,name=genres,proto3" json:"genres,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	TotalChapters int32                  `protobuf:"varint,6,opt,name=total_chapters,json=totalChapters,proto3" json:"total_chapters,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,8,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MangaResponse) Reset() {
	*x = MangaResponse{}
	mi := &file_proto_manga_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaResponse) ProtoMessage() {}

func (x *MangaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaResponse.ProtoReflect.Descriptor instead.
func (*MangaResponse) Descriptor() ([]byte, []int) {
	return file_proto_manga_proto_rawDescGZIP(), []int{1}
}

func (x *MangaResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MangaResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MangaResponse) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *MangaResponse) GetGenres() []*Genre {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *MangaResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MangaResponse) GetTotalChapters() int32 {
	if x != nil {
		return x.TotalChapters
	}
	return 0
}

func (x *MangaResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MangaResponse) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

type GetMangaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMangaRequest) Reset() {
	*x = GetMangaRequest{}
	mi := &file_proto_manga_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMangaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMangaRequest) ProtoMessage() {}

func (x *GetMangaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMangaRequest.ProtoReflect.Descriptor instead.
func (*GetMangaRequest) Descriptor() ([]byte, []int) {
	return file_proto_manga_proto_rawDescGZIP(), []int{2}
}

func (x *GetMangaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Genre         []string               `protobuf:"bytes,2,rep,name=genre,proto3" json:"genre,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_manga_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_manga_proto_rawDescGZIP(), []int{3}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetGenre() []string {
	if x != nil {
		return x.Genre
	}
	return nil
}

func (x *SearchRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SearchRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mangas        []*MangaResponse       `protobuf:"bytes,1,rep,name=mangas,proto3" json:"mangas,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_proto_manga_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_manga_proto_rawDescGZIP(), []int{4}
}

func (x *SearchResponse) GetMangas() []*MangaResponse {
	if x != nil {
		return x.Mangas
	}
	return nil
}

func (x *SearchResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ProgressRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MangaId        string                 `protobuf:"bytes,2,opt,name=manga_id,json=mangaId,proto3" json:"manga_id,omitempty"`
	CurrentChapter int32                  `protobuf:"varint,3,opt,name=current_chapter,json=currentChapter,proto3" json:"current_chapter,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProgressRequest) Reset() {
	*x = ProgressRequest{}
	mi := &file_proto_manga_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressRequest) ProtoMessage() {}

func (x *ProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressRequest.ProtoReflect.Descriptor instead.
func (*ProgressRequest) Descriptor() ([]byte, []int) {
	return file_proto_manga_proto_rawDescGZIP(), []int{5}
}

func (x *ProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProgressRequest) GetMangaId() string {
	if x != nil {
		return x.MangaId
	}
	return ""
}

func (x *ProgressRequest) GetCurrentChapter() int32 {
	if x != nil {
		return x.CurrentChapter
	}
	return 0
}

func (x *ProgressRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressResponse) Reset() {
	*x = ProgressResponse{}
	mi := &file_proto_manga_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressResponse) ProtoMessage() {}

func (x *ProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressResponse.ProtoReflect.Descriptor instead.
func (*ProgressResponse) Descriptor() ([]byte, []int) {
	return file_proto_manga_proto_rawDescGZIP(), []int{6}
}

func (x *ProgressResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProgressResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RatingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MangaId       string                 `protobuf:"bytes,2,opt,name=manga_id,json=mangaId,proto3" json:"manga_id,omitempty"`
	Rating        int32                  `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RatingRequest) Reset() {
	*x = RatingRequest{}
	mi := &file_proto_manga_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatingRequest) ProtoMessage() {}

func (x *RatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatingRequest.ProtoReflect.Descriptor instead.
func (*RatingRequest) Descriptor() ([]byte, []int) {
	return file_proto_manga_proto_rawDescGZIP(), []int{7}
}

func (x *RatingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RatingRequest) GetMangaId() string {
	if x != nil {
		return x.MangaId
	}
	return ""
}

func (x *RatingRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type RatingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Average       float32                `protobuf:"fixed32,3,opt,name=average,proto3" json:"average,omitempty"`
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RatingResponse) Reset() {
	*x = RatingResponse{}
	mi := &file_proto_manga_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RatingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatingResponse) ProtoMessage() {}

func (x *RatingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatingResponse.ProtoReflect.Descriptor instead.
func (*RatingResponse) Descriptor() ([]byte, []int) {
	return file_proto_manga_proto_rawDescGZIP(), []int{8}
}

func (x *RatingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RatingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RatingResponse) GetAverage() float32 {
	if x != nil {
		return x.Average
	}
	return 0
}

func (x *RatingResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_proto_manga_proto protoreflect.FileDescriptor

const file_proto_manga_proto_rawDesc = "" +
	"\n" +
	"\x11proto/manga.proto\x12\x05manga\"+\n" +
	"\x05Genre\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xf1\x01\n" +
	"\rMangaResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12$\n" +
	"\x06genres\x18\x04 \x03(\v2\f.manga.GenreR\x06genres\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12%\n" +
	"\x0etotal_chapters\x18\x06 \x01(\x05R\rtotalChapters\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x1b\n" +
	"\tcover_url\x18\b \x01(\tR\bcoverUrl\"!\n" +
	"\x0fGetMangaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"}\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05genre\x18\x02 \x03(\tR\x05genre\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"T\n" +
	"\x0eSearchResponse\x12,\n" +
	"\x06mangas\x18\x01 \x03(\v2\x14.manga.MangaResponseR\x06mangas\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x86\x01\n" +
	"\x0fProgressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bmanga_id\x18\x02 \x01(\tR\amangaId\x12'\n" +
	"\x0fcurrent_chapter\x18\x03 \x01(\x05R\x0ecurrentChapter\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"F\n" +
	"\x10ProgressResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"[\n" +
	"\rRatingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bmanga_id\x18\x02 \x01(\tR\amangaId\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\x05R\x06rating\"t\n" +
	"\x0eRatingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\aaverage\x18\x03 \x01(\x02R\aaverage\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count2\x81\x02\n" +
	"\fMangaService\x128\n" +
	"\bGetManga\x12\x16.manga.GetMangaRequest\x1a\x14.manga.MangaResponse\x12:\n" +
	"\vSearchManga\x12\x14.manga.SearchRequest\x1a\x15.manga.SearchResponse\x12A\n" +
	"\x0eUpdateProgress\x12\x16.manga.ProgressRequest\x1a\x17.manga.ProgressResponse\x128\n" +
	"\tRateManga\x12\x14.manga.RatingRequest\x1a\x15.manga.RatingResponseB\x15Z\x13managahub/pkg/protob\x06proto3"

var (
	file_proto_manga_proto_rawDescOnce sync.Once
	file_proto_manga_proto_rawDescData []byte
)

func file_proto_manga_proto_rawDescGZIP() []byte {
	file_proto_manga_proto_rawDescOnce.Do(func() {
		file_proto_manga_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_manga_proto_rawDesc), len(file_proto_manga_proto_rawDesc)))
	})
	return file_proto_manga_proto_rawDescData
}

var file_proto_manga_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_manga_proto_goTypes = []any{
	(*Genre)(nil),            // 0: manga.Genre
	(*MangaResponse)(nil),    // 1: manga.MangaResponse
	(*GetMangaRequest)(nil),  // 2: manga.GetMangaRequest
	(*SearchRequest)(nil),    // 3: manga.SearchRequest
	(*SearchResponse)(nil),   // 4: manga.SearchResponse
	(*ProgressRequest)(nil),  // 5: manga.ProgressRequest
	(*ProgressResponse)(nil), // 6: manga.ProgressResponse
	(*RatingRequest)(nil),    // 7: manga.RatingRequest
	(*RatingResponse)(nil),   // 8: manga.RatingResponse
}
var file_proto_manga_proto_depIdxs = []int32{
	0, // 0: manga.MangaResponse.genres:type_name -> manga.Genre
	1, // 1: manga.SearchResponse.mangas:type_name -> manga.MangaResponse
	2, // 2: manga.MangaService.GetManga:input_type -> manga.GetMangaRequest
	3, // 3: manga.MangaService.SearchManga:input_type -> manga.SearchRequest
	5, // 4: manga.MangaService.UpdateProgress:input_type -> manga.ProgressRequest
	7, // 5: manga.MangaService.RateManga:input_type -> manga.RatingRequest
	1, // 6: manga.MangaService.GetManga:output_type -> manga.MangaResponse
	4, // 7: manga.MangaService.SearchManga:output_type -> manga.SearchResponse
	6, // 8: manga.MangaService.UpdateProgress:output_type -> manga.ProgressResponse
	8, // 9: manga.MangaService.RateManga:output_type -> manga.RatingResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_manga_proto_init() }
func file_proto_manga_proto_init() {
	if File_proto_manga_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_manga_proto_rawDesc), len(file_proto_manga_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_manga_proto_goTypes,
		DependencyIndexes: file_proto_manga_proto_depIdxs,
		MessageInfos:      file_proto_manga_proto_msgTypes,
	}.Build()
	File_proto_manga_proto = out.File
	file_proto_manga_proto_goTypes = nil
	file_proto_manga_proto_depIdxs = nil
}
